id: P6A466669
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1GS60700
  instance_id: http://purl.bdrc.io/resource/IE1GS60700
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - གསོ་རིག་ལག་ལེན་སྤྱི་དོན་སྒྲོན་མ།
  alt_title: {}
  author: http://purl.bdrc.io/resource/P1GS58822
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    80410ba6e075443aa43a6b8523e2668d:
      title: པོད ༡་གསོ་རིག་ལག་ལེན་སྤྱི་དོན་སྒྲོན་མ
      volume_number: 1
      base_file: UT1GS60700_I1GS60702_0000.txt
      reference: http://purl.bdrc.io/resource/VLE8200902517F3354
      image_group: I1GS60702
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1GS60700
  - http://purl.bdrc.io/resource/MW1GS60700
  ocr_software: Namsel
created_at: '2021-12-22T10:27:47.465818'
last_modified_at: '2021-12-22T10:27:47.465825'
